# Generated by Django 3.1.4 on 2020-12-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
